(** [EML_runtime] provides runtime utilities for the code generated by the EML
    compiler. *)

(** [escape s] is the HTML-escaped version of the string [s].
    Characters '&', '<', '>', '"' and ''' are replaced by their HTMl encoding. *)
let escape s =
  let buffer = Buffer.create (String.length s) in
  String.iter
    (function
      | '&' -> Buffer.add_string buffer "&amp;"
      | '<' -> Buffer.add_string buffer "&lt;"
      | '>' -> Buffer.add_string buffer "&gt;"
      | '"' -> Buffer.add_string buffer "&quot;"
      | '\'' -> Buffer.add_string buffer "&#x27;"
      | c -> Buffer.add_char buffer c )
    s ;
  Buffer.contents buffer